on:
  pull_request:
  push:
    branches: [master]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check
      - run: |
          features=("" "linux_5-5" "linux_5-7")
          for feature in "${features[@]}"; do
              echo testing feature $features
              # Need to use this syntax for `feature` so that it correctly passes the empty string.
              cargo clippy --workspace --all-targets --no-default-features --features "${feature[@]}" -- -D warnings
              cargo test --workspace --no-default-features --features "${feature[@]}"
          done
